from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from io import BytesIO

def generate_enhanced_pdf_report(df, col_types, insights):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=(8.5*inch, 11*inch), topMargin=inch)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle('title', parent=styles['Heading1'], alignment=1, fontSize=24, spaceAfter=20)
    story.append(Paragraph("📊 Intelligent Data Analysis Report", title_style))

    # Numeric summary example
    if col_types["numeric"]:
        story.append(Paragraph("Numeric Columns Summary:", styles['Heading2']))
        data = [["Column", "Mean", "Std Dev", "Min", "Max", "Missing"]]
        for col in col_types["numeric"]:
            data.append([
                col,
                f"{df[col].mean():.2f}",
                f"{df[col].std():.2f}",
                f"{df[col].min():.2f}",
                f"{df[col].max():.2f}",
                f"{df[col].isnull().sum()}"
            ])
        table = Table(data, hAlign="LEFT")
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ]))
        story.append(table)
        story.append(Spacer(1, 20))

    # Insights Section (with fallback)
    story.append(Paragraph("Key Insights and Recommendations:", styles['Heading2']))
    if not insights or (isinstance(insights, str) and not insights.strip()):
        insights = ["No major issues detected. The data appears clean and ready for analysis."]
    elif isinstance(insights, str):
        insights = [insights]
    for ins in insights:
        story.append(Paragraph(f"• {ins}", styles['Normal']))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Intelligent Data Analysis Assistant", styles['Normal']))

    doc.build(story)
    buffer.seek(0)
    return buffer
